name: Setup pipx
description: Setup pipx for GitHub Actions

inputs:
  pipx-version:
    description: The version of pipx to use.
    required: false

runs:
  using: composite
  steps:
    # Linux, macOS

    - run: mkdir -p $HOME/.local
      if: runner.os != 'Windows'
      shell: bash
    - run: echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV
      if: runner.os != 'Windows'
      shell: bash
    - run: echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
      if: runner.os != 'Windows'
      shell: bash
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      if: runner.os != 'Windows'
      shell: bash
    # todo: remove /opt/pipx_bin from $PATH

    - run: python -m venv ../pipx_venv
      if: runner.os != 'Windows'
      shell: bash
    - run: ../pipx_venv/bin/python -m pip install pipx
      if: ${{ runner.os != 'Windows' && inputs.pipx-version == '' }}
      shell: bash
    - run: ../pipx_venv/bin/python -m pip install pipx==${{ inputs.pipx-version }}
      if: ${{ runner.os != 'Windows' && inputs.pipx-version != '' }}
      shell: bash
    - run: mv /usr/local/bin/pipx /usr/local/bin/pipx_orig
      if: runner.os != 'Windows'
      shell: bash
    - run: cp ../pipx_venv/bin/pipx /usr/local/bin/pipx
      if: runner.os != 'Windows'
      shell: bash

    - run: pipx ensurepath
      if: runner.os != 'Windows'
      shell: bash


    # Windows
    
    - run: mkdir -p $HOME\.local
      if: runner.os == 'Windows'
      shell: pwsh
    - run: echo "PIPX_BIN_DIR=$HOME\.local\bin" >> $GITHUB_ENV
      if: runner.os == 'Windows'
      shell: pwsh
    - run: echo "PIPX_HOME=$HOME\.local\pipx" >> $GITHUB_ENV
      if: runner.os == 'Windows'
      shell: pwsh
    - run: echo "$HOME\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      if: runner.os == 'Windows'
      shell: pwsh
    # todo: remove /c/Program Files (x86)/pipx_bin from $PATH
      
    - run: python -m venv ..\pipx_venv
      if: runner.os == 'Windows'
      shell: pwsh
    - run: ..\pipx_venv\Scripts\python -m pip install pipx
      if: ${{ runner.os == 'Windows' && inputs.pipx-version == '' }}
      shell: pwsh
    - run: ..\pipx_venv\Scripts\python -m pip install pipx==${{ inputs.pipx-version }}
      if: ${{ runner.os == 'Windows' && inputs.pipx-version != '' }}
      shell: pwsh
    - run: mv "C:\Program Files (x86)\pipx_bin\pipx.exe" "C:\Program Files (x86)\pipx_bin\pipx_orig.exe"
      if: runner.os == 'Windows'
      shell: pwsh
    - run: cp ..\pipx_venv\Scripts\pipx.exe "C:\Program Files (x86)\pipx_bin\pipx.exe"
      if: runner.os == 'Windows'
      shell: pwsh

    - run: pipx ensurepath
      if: runner.os == 'Windows'
      shell: pwsh
