name: Pipx setup
description: Pipx setup for GitHub Actions

runs:
  using: composite
  steps:
    - run: python -m venv /opt/pipx_venv
      shell: bash
    - run: /opt/pipx_venv/bin/python -m pip install pipx
      shell: bash
    - run: mv /usr/local/bin/pipx /usr/local/bin/pipx_orig
      shell: bash
    - run: cp /opt/pipx_venv/bin/pipx /usr/local/bin/pipx
      shell: bash
    - run: echo "/.local/bin" >> $GITHUB_PATH
      shell: bash
