name: Creosote action
description: Pipx setup for GitHub Actions

runs:
  using: composite
  steps:
    - run: python -m pip install pipx
      shell: bash
    - run: pipx ensurepath
      shell: bash
    - run: echo "/.local/bin" >> $GITHUB_PATH
      shell: bash
